
FROM golang:1.24.9-alpine3.22 AS builder

WORKDIR /myapp

COPY ./cmd/info/main.go .
COPY ./go.mod .

RUN go mod tidy

RUN go build -o appinfo /myapp/main.go

FROM alpine:3.22

WORKDIR /myapp

COPY --from=builder /myapp/appinfo .

CMD [ "/myapp/appinfo" ]